import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Layout from "@/commons/layout/02-02-layout-header-global"
import LayoutGlobalAndLocal from "@/commons/layout/02-03-layout-header-local";
import LayoutTransparent from "@/commons/layout/02-04-layout-header-transparent";
import LayoutFooter from "@/commons/layout/02-05-layout-footer";
import DeviceSettingVariables from "@/commons/settings/05-01-device-setting-variables";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",

});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 1). 02-02-layout-header-global 수업에서 진행  */}
        {/* <Layout>{children}</Layout> */}
        
      {/* 2.). 02-03-layout-header-local 수업에서 진행  */} 
      {/* <LayoutGlobalAndLocal>{children}</LayoutGlobalAndLocal> */}
      
      {/* 3). 02-04-layout-header-transparent 수업에서 진행  */}
     {/* <LayoutTransparent>(children)</LayoutTransparent> */}

   
       {/*4). 02-05-layout-footer 수업에서 진행 */ }
      {/* <LayoutFooter>{children}</LayoutFooter> */}

      { /*5). 03-06-post-message-device-api-proimise-refactoring 수업에서 진행 */}

      { /*6). 04-01-device-system-api 수업에서 진행 */}
        {/* <DeviceSetting> {children}</DeviceSetting> */}


      { /*7). 04-02-device-location-api 수업에서 진행 */}
        {/* <DeviceSetting> {children}</DeviceSetting> */}

         { /*8). 04-03-device-api-refactoring 수업에서 진행 */}
         {/* <DeviceSetting> {children}</DeviceSetting>  */}

        { /*9). 05-01-schedule-notifications 수업에서 진행 */}
         {/* <DeviceSettingVariables> {children}</DeviceSettingVariables>  */}

        { /*10). 05-02-schedule-notifications-click 수업에서 진행 */}
         <DeviceSettingRedirect> {children}</DeviceSettingRedirect>
      </body>
    </html>
  );
}
